import fs from 'fs/promises';
import path from 'path';
import { execSync } from 'child_process';

export class ProjectAgent {
  constructor(llm, tools) {
    this.llm = llm;
    this.tools = tools;
  }
  
  async initializeProject(name, type = 'node', options = {}) {
    const templates = {
      node: {
        files: {
          'package.json': JSON.stringify({
            name: name,
            version: '1.0.0',
            description: options.description || '',
            main: options.entry || 'index.js',
            scripts: {
              start: 'node index.js',
              dev: 'nodemon index.js',
              test: 'jest',
              build: 'echo "Build not configured"'
            },
            dependencies: {},
            devDependencies: {
              jest: '^29.0.0',
              nodemon: '^3.0.0'
            }
          }, null, 2),
          'index.js': `// Main entry point for ${name}
console.log('🚀 Starting ${name}...');

function main() {
  console.log('✓ Application running');
  // Add your code here
}

if (require.main === module) {
  main();
}

module.exports = { main };
`,
          'README.md': `# ${name}

## Installation

\`\`\`bash
npm install
\`\`\`

## Usage

\`\`\`bash
npm start
\`\`\`

## Development

\`\`\`bash
npm run dev
\`\`\`

## Tests

\`\`\`bash
npm test
\`\`\`

## License

MIT
`,
          '.gitignore': `node_modules/
dist/
build/
.env
.DS_Store
*.log
coverage/
`,
          '.env.example': `# Environment variables for ${name}
PORT=3000
NODE_ENV=development
`
        },
        setup: async () => {
          execSync('npm init -y', { stdio: 'ignore' });
        }
      },
      
      python: {
        files: {
          'requirements.txt': '# Dependencies for ' + name + '\n# Add your packages here\n',
          'main.py': `#!/usr/bin/env python3
\"\"\"Main entry point for ${name}\"\"\"

import sys

def main():
    \"\"\"Main function\"\"\"
    print(f"🚀 Starting {name}...")
    print("✓ Application running")
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
          'README.md': `# ${name}

## Setup

\`\`\`bash
pip install -r requirements.txt
\`\`\`

## Usage

\`\`\`bash
python main.py
\`\`\`

## License

MIT
`,
          '.gitignore': `__pycache__/
*.pyc
.env
venv/
dist/
build/
*.egg-info/
`,
          'setup.py': `from setuptools import setup, find_packages

setup(
    name="${name}",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[],
    author="Cod3x",
    description="Generated by Cod3x-Code",
    license="MIT",
)
`
        },
        setup: async () => {
          execSync('python3 -m venv venv', { stdio: 'ignore' });
        }
      },
      
      go: {
        files: {
          'go.mod': `module ${name}

go 1.21
`,
          'main.go': `package main

import (
    "fmt"
    "os"
)

func main() {
    fmt.Println("🚀 Starting ${name}...")
    fmt.Println("✓ Application running")
    os.Exit(0)
}
`,
          'README.md': `# ${name}

## Build

\`\`\`bash
go build
\`\`\`

## Run

\`\`\`bash
./${name}
\`\`\`

## License

MIT
`,
          '.gitignore': `/${name}
*.exe
*.test
*.out
coverage.txt
`
        },
        setup: async () => {
          execSync('go mod tidy', { stdio: 'ignore' });
        }
      }
    };
    
    const template = templates[type] || templates.node;
    
    // Create project directory if needed
    await fs.mkdir(name, { recursive: true });
    process.chdir(name);
    
    // Create all files
    for (const [filePath, content] of Object.entries(template.files)) {
      const fullPath = path.join(process.cwd(), filePath);
      const dir = path.dirname(fullPath);
      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(fullPath, content, 'utf-8');
    }
    
    // Run setup
    if (template.setup) await template.setup();
    
    return {
      success: true,
      project: name,
      type: type,
      files: Object.keys(template.files).length,
      message: `✓ Created ${type} project: ${name}`
    };
  }
  
  async scaffoldComponent(name, type = 'react', options = {}) {
    const prompt = `Create a complete, production-ready ${type} component named "${name}".

Requirements:
- Full implementation with all necessary code
- Props/parameters validation
- Error boundaries (for React)
- Styling (CSS/Tailwind/modules)
- Usage examples
- Documentation comments

${options.additional || ''}

Return the complete component code.`;
    
    const code = await this.llm.chat(prompt);
    
    return {
      name: name,
      type: type,
      code: code,
      path: `src/components/${name}.${type === 'react' ? 'jsx' : 'js'}`
    };
  }
  
  async addDependency(dependency, isDev = false) {
    const cmd = `npm install ${isDev ? '--save-dev' : '--save'} ${dependency}`;
    
    try {
      execSync(cmd, { stdio: 'pipe', encoding: 'utf-8' });
      return {
        success: true,
        dependency: dependency,
        isDev: isDev,
        message: `✓ Installed ${dependency}`
      };
    } catch (error) {
      return {
        success: false,
        dependency: dependency,
        error: error.message
      };
    }
  }
  
  async analyzeProject() {
    const stats = {
      files: 0,
      lines: 0,
      dependencies: {},
      scripts: {},
      structure: {}
    };
    
    // Count files and lines
    const { glob } = await import('glob');
    const files = await glob('**/*.{js,ts,jsx,tsx,py,go,md,json}', {
      ignore: ['node_modules/**', '.git/**', 'dist/**', 'build/**']
    });
    
    stats.files = files.length;
    
    for (const file of files.slice(0, 100)) {
      try {
        const content = await fs.readFile(file, 'utf-8');
        stats.lines += content.split('\n').length;
      } catch (error) {}
    }
    
    // Read package.json if exists
    try {
      const pkg = JSON.parse(await fs.readFile('package.json', 'utf-8'));
      stats.dependencies = pkg.dependencies || {};
      stats.scripts = pkg.scripts || {};
    } catch (error) {}
    
    return stats;
  }
  
  async generateDockerfile(type = 'node') {
    const dockerfiles = {
      node: `FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3000

CMD ["node", "index.js"]
`,
      python: `FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
`,
      go: `FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /app/app .

CMD ["./app"]
`
    };
    
    return dockerfiles[type] || dockerfiles.node;
  }
  
  async scaffoldApi(resource, options = {}) {
    const prompt = `Create a complete REST API for resource "${resource}" with:
- CRUD operations (Create, Read, Update, Delete)
- Input validation
- Error handling
- Database integration (${options.database || 'SQLite'})
- Proper HTTP status codes

Return the complete implementation.`;
    
    return await this.llm.chat(prompt);
  }
}

export default ProjectAgent;
